// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK7yEDGFmJEY7TVi9fegYgDvV_UeVM3xg',
    appId: '1:652524923023:web:e56a43d34db7f11eece8fa',
    messagingSenderId: '652524923023',
    projectId: 'moeda-verde-fausta-hom',
    authDomain: 'moeda-verde-fausta-hom.firebaseapp.com',
    storageBucket: 'moeda-verde-fausta-hom.firebasestorage.app',
    measurementId: 'G-LM7JEZHJS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGPGwhKGu50w91t5tVCZivwstBtu-wGuE',
    appId: '1:652524923023:android:4f7cbf9e8163d55dece8fa',
    messagingSenderId: '652524923023',
    projectId: 'moeda-verde-fausta-hom',
    storageBucket: 'moeda-verde-fausta-hom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuY7O5ZvtYb7ZLLlzxtmH-ht5asnnY-g',
    appId: '1:652524923023:ios:76988a5f5ee9a196ece8fa',
    messagingSenderId: '652524923023',
    projectId: 'moeda-verde-fausta-hom',
    storageBucket: 'moeda-verde-fausta-hom.firebasestorage.app',
    iosBundleId: 'com.example.moedaVerde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuY7O5ZvtYb7ZLLlzxtmH-ht5asnnY-g',
    appId: '1:652524923023:ios:76988a5f5ee9a196ece8fa',
    messagingSenderId: '652524923023',
    projectId: 'moeda-verde-fausta-hom',
    storageBucket: 'moeda-verde-fausta-hom.firebasestorage.app',
    iosBundleId: 'com.example.moedaVerde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK7yEDGFmJEY7TVi9fegYgDvV_UeVM3xg',
    appId: '1:652524923023:web:8620b81474f1c0b7ece8fa',
    messagingSenderId: '652524923023',
    projectId: 'moeda-verde-fausta-hom',
    authDomain: 'moeda-verde-fausta-hom.firebaseapp.com',
    storageBucket: 'moeda-verde-fausta-hom.firebasestorage.app',
    measurementId: 'G-5B9BXW9HPJ',
  );

}